<?php
class Modelos_Insumos extends Sfphp_Modelo 
{
	public function __construct() {
	# Crear la conexion
		$this->db = Sfphp_BaseDatos::get("ordprod");
	}

	public function get()
	{
		$query = "SELECT ORD_FAB01.NUM_REG, ORD_FAB01.CLAVE, ORD_FAB01.PRODUCTO, ORD_FAB01.CANTIDAD, ORD_FAB01.PRIORIDAD, ORD_FAB01.FCAPTURA, ORD_FAB01.FENTREGA, ORD_FAB01.FINICIAL, ORD_FAB01.FTERMINA, ORD_FAB01.CANTTERM, ORD_FAB01.TGASDIR, ORD_FAB01.TGASIND, ORD_FAB01.FULTMOV, ORD_FAB01.REFERENCIA, ORD_FAB01.COSTEST, ORD_FAB01.TIPOCTO, ORD_FAB01.TIPOORD, ORD_FAB01.STATUS, ORD_FAB01.STATUSAV, ORD_FAB01.PROCESO, ORD_FAB01.NUMUSU, ORD_FAB01.REGSERIE, ORD_FAB01.OCUPADO, ORD_FAB01.ACT_SAE, ORD_FAB01.HRSXDIA, ORD_FAB01.OBSORD, ORD_FAB01.CVELOTE, ORD_FAB01.FCHCADUC, ORD_FAB01.FCHPRODUC, ORD_FAB01.REGLOTE, ORD_FAB01.RESTO
			FROM ORD_FAB01 ORD_FAB01;";
		return $this->query($query);
	}
}